name: 'Add NuGet package source'
description: 'Adds NuGet package source to the system if it is not already added and cleans it after the job is finished'
author: 'deitry'
branding:
  icon: package
  color: green

inputs:
  url:
    required: true
    description: 'Url of NuGet package source to add'
  username:
    required: false
    description: 'Username for private NuGet package source access'
  password:
    required: false
    description: 'Password for private NuGet package source access'

runs:
  using: 'node20'
  main: 'dist/main.js'
  post: dist/post.js
